#!/bin/bash

set -e
rm -r "output/run_0"
python smac --scenario scenario.txt \
            --output-dir output \
            --algo "./alg.py" \
            --paramfile param.pcs \
            --seed 0 \
            --deterministic 1 \
            --run_obj "quality" \
            --wallclock-limit 10
