stages:
  - test

test ECTS:
  stage: test
    rules:
      - chages:
        - ECTS
  script:
    - pushd ECTS
    - make test
    - pwd

test paramils:
    stage: test
    rules:
      - chages:
        - paramils
    script:
      - paramils/test

