#!/usr/bin/env bash

echo "TEST:   ECTS"
pushd ECTS > /dev/null && make test && echo "PASSED: ECTS" || echo "FAILED: ECTS"
popd > /dev/null

echo "TEST:   RelClass"
pushd RelClass > /dev/null && ./test  && echo "PASSED: RelClass" || echo "FAILED: RelClass"
popd > /dev/null