# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distSqrd <- function(Ar, Br) {
    .Call(`_fastDistSqrd_distSqrd`, Ar, Br)
}

distcpp <- function(Ar, Br) {
    .Call(`_fastDistSqrd_distcpp`, Ar, Br)
}

