/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ECEC;

public class Ap {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new Ap().getGreeting());
    }
}
