#!/usr/bin/env bash
set -e

for data in {"Coffee","Herring"}; do
    train="../data/${data}_TRAIN.tsv"
    test="../data/${data}_TEST.tsv"
    ./run -data $train $test -tau 1e-30 -constr 'boxco' -ldg 1
    ./run -data $train $test -tau 1e-16 -constr 'Naive' -ldg 1
    ./run -data $train $test -tau 1e-4  -constr 'Cheby' -ldg 1
    ./run -data $train $test -tau 1e-0  -constr 'boxco' -ldg 0
done
